[tool.poetry]
name = "factorial_namtao"
version = "0.1.0"
description = ""
authors = ["namtao <vannam.pxb@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.32.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
